apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-v2
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cloud-local-storage
  local:
    path: /root/data/volume2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-worker